# Generated by Django 4.2.22 on 2025-06-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocoordinates', '0001_initial'),
        ('foodcartapp', '0046_order_restaurant_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='geocoded_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_restaurants', to='geocoordinates.geocodedaddress', verbose_name='Геокодированный адрес ресторана'),
        ),
    ]
