# Generated by Django 4.2.22 on 2025-06-18 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, help_text='Широта полученная от геокодера', null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, help_text='Долгота полученная от геокодера', null=True, verbose_name='Долгота')),
                ('queried_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последнего успешного запроса к геокодеру для этого адреса', verbose_name='Дата запроса к геокодеру')),
            ],
            options={
                'verbose_name': 'Геокодированный адрес',
                'verbose_name_plural': 'Геокодированные адреса',
            },
        ),
    ]
