# Generated by Django 4.2.22 on 2025-06-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phonenumber',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lastname',
            new_name='surname',
        ),
    ]
