# Generated by Django 4.2.22 on 2025-06-13 22:19

from django.db import migrations


def fill_price_at_purchase(apps, schema_editor):
    """
    Заполняет поле price_at_purchase для существующих позиций заказа,
    используя текущую цену соответствующего продукта.
    """
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    Product = apps.get_model('foodcartapp', 'Product')

    for order_item in OrderItem.objects.select_related('product').iterator():

        if order_item.price_at_purchase == 0 or order_item.price_at_purchase is None:

            order_item.price_at_purchase = order_item.product.price
            order_item.save(update_fields=['price_at_purchase'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_price_at_purchase, reverse_code=migrations.RunPython.noop),
    ]
