# Generated by Django 4.2.22 on 2025-06-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_fill_price_at_purchase_for_old_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработан'), ('PREPARING', 'Готовится'), ('DELIVERING', 'В доставке'), ('COMPLETED', 'Выполнен'), ('CANCELED', 'Отменён')], db_index=True, default='NEW', max_length=50, verbose_name='Статус заказов'),
        ),
    ]
