# Generated by Django 4.2.22 on 2025-06-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_comment',
            field=models.TextField(blank=True, help_text='Примечания к заказу', null=True, verbose_name='Комментарий'),
        ),
    ]
