# Generated by Django 4.2.22 on 2025-06-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_called_at_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными при получении'), ('card', 'Электронно')], db_index=True, default='cash', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
