# Generated by Django 4.2.22 on 2025-06-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocoordinates', '0001_initial'),
        ('foodcartapp', '0047_restaurant_geocoded_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='geocoded_delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_orders', to='geocoordinates.geocodedaddress', verbose_name='Геокодированный адрес доставки'),
        ),
    ]
