# Generated by Django 4.2.22 on 2025-06-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_geocoded_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_comment',
            field=models.TextField(blank=True, default='', help_text='Примечания к заказу', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
