# Generated by Django 4.2.22 on 2025-08-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_geocoded_delivery_address_and_more'),
        ('foodcartapp', '0049_alter_order_customer_comment'),
    ]

    operations = [
    ]
